import Head from 'next/head'
import React, { useState} from 'react';
import CookieStandHeader from '../components/header'
import CookieStandForm from '../components/main'
import Footer from '../components/footer'


export default function Home(){
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>
          Cookie Stand Admin
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CookieStandHeader />

      <CookieStandForm />
      <p>
        Report Table comming soon .....
        </p>
        <Footer />
    </div>
  )
}